package com.meikai.common.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import com.meikai.HomepageAuthRes;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HomepageAuthentification", targetNamespace = "http://smp.blossom.com")
public interface HomepageService {

	/**
	 * 
	 * @param arg0
	 * @return returns com.meikai.HomepageAuthRes
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public HomepageAuthRes homepageAuth(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

}
